# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

target 'DouYuTV' do


  # Pods for DouYuTV

  target 'DouYuTVTests' do
    inherit! :search_paths
    pod 'Alamofire'
  end

  target 'DouYuTVUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
